// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

/*
type Rack struct {
	ID           int                  `json:"Id"`
	Name         string               `json:"Name"`
	Created      *string              `json:"Created"`
	CustomFields *entity.CustomFields `json:"CustomFields"`
}
*/

type Role struct {
	ID   int     `json:"Id"`
	Name *string `json:"Name"`
}

type Status struct {
	Label *string `json:"Label"`
	Value *int    `json:"Value"`
}
